-- Seed de contenido — M2 (enriquecido), M4, M5
-- Generado por gen.py; cada bloque JSONB validado ejecutándolo.
-- Idempotente: on conflict (id) do update.

-- ===== m2 =====
insert into exercises (id, node_id, type, position, content) values
  ('m2-fixbug1', 'm2-data-structures', 'fix_bug', 20, '{"prompt": "La función añade un elemento a una lista y la devuelve. Llamada varias veces sin pasar lista, debería devolver siempre una lista de un solo elemento, pero acumula. Arréglalo.", "starter_code": "def añadir(x, lista=[]):\n    lista.append(x)\n    return lista", "tests": [{"call": "añadir(1); añadir(2)", "expected": "[2]"}, {"call": "añadir(5, [1, 2])", "expected": "[1, 2, 5]"}, {"call": "añadir(''a'') == [''a'']", "expected": "True"}], "hints": ["Los valores por defecto se evalúan una sola vez, al definir la función, no en cada llamada.", "Usa un valor por defecto inmutable (None) como centinela y crea la lista dentro.", "if lista is None: lista = []"], "solution": "def añadir(x, lista=None):\n    if lista is None:\n        lista = []\n    lista.append(x)\n    return lista", "meta": {"difficulty": 2, "interview": true, "concepts": ["argumentos por defecto mutables", "listas"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m2-predict1', 'm2-data-structures', 'predict_output', 21, '{"prompt": "¿Qué imprime este código? Razona sobre qué comparten las variables y qué no.", "code": "a = [1, 2, 3]\nb = a\nc = a[:]\nb.append(4)\nc.append(5)\nprint(a)\nprint(c)\nprint(a is b, a is c)", "expected_output": "[1, 2, 3, 4]\n[1, 2, 3, 5]\nTrue False", "explanation": "b = a no copia nada: ambos nombres apuntan a la misma lista, así que el append a b también se ve en a. a[:] crea una copia nueva (superficial), por eso c evoluciona aparte. is compara identidad, no contenido.", "meta": {"difficulty": 2, "interview": true, "concepts": ["aliasing", "copia superficial", "is vs =="]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m2-match1', 'm2-data-structures', 'match', 22, '{"prompt": "Une cada construcción con lo que produce.", "pairs": [{"term": "[x*2 for x in range(3)]", "definition": "Una lista completa en memoria: [0, 2, 4]"}, {"term": "(x*2 for x in range(3))", "definition": "Un generador perezoso: produce valores solo al iterarlo"}, {"term": "{x: x*2 for x in range(3)}", "definition": "Un diccionario: {0: 0, 1: 2, 2: 4}"}, {"term": "{x*2 for x in range(3)}", "definition": "Un conjunto sin duplicados ni orden garantizado"}, {"term": "list(map(lambda x: x*2, range(3)))", "definition": "La misma lista que la comprensión, con estilo funcional"}], "meta": {"difficulty": 2, "interview": false, "concepts": ["comprensiones", "generadores"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m2-parsons1', 'm2-data-structures', 'parsons', 23, '{"prompt": "Ordena las líneas para contar cuántas veces aparece cada palabra en una lista, usando dict.get con valor por defecto.", "lines": ["def contar(palabras):", "    conteo = {}", "    for p in palabras:", "        conteo[p] = conteo.get(p, 0) + 1", "    return conteo"], "meta": {"difficulty": 1, "interview": false, "concepts": ["diccionarios", "dict.get"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== m4 =====
insert into exercises (id, node_id, type, position, content) values
  ('m4-e1', 'm4-testing-errors', 'recall', 1, '{"prompt": "Calentamiento (M3): explica con tus palabras qué hace `super().__init__()` dentro del constructor de una clase hija y qué pasaría si lo omites.", "isCode": false, "modelAnswer": "Llama al constructor de la clase padre para que inicialice sus propios atributos. Si lo omites, los atributos que el padre define en su __init__ no existen en la instancia y cualquier método heredado que los use fallará con AttributeError.", "meta": {"difficulty": 1, "interview": true, "concepts": ["herencia", "super"], "recuerda_de": "m3-oop"}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e2', 'm4-testing-errors', 'predict_output', 2, '{"prompt": "¿Qué imprime? Fíjate en el orden en que se ejecutan try, except, else y finally.", "code": "def dividir(a, b):\n    try:\n        r = a / b\n    except ZeroDivisionError:\n        print(''division por cero'')\n        return None\n    else:\n        print(''sin error'')\n        return r\n    finally:\n        print(''limpieza'')\n\nprint(dividir(6, 3))\nprint(dividir(1, 0))", "expected_output": "sin error\nlimpieza\n2.0\ndivision por cero\nlimpieza\nNone", "explanation": "else solo corre si no hubo excepción; finally corre siempre, incluso después de un return. Por eso ''limpieza'' aparece antes de que el print exterior muestre el valor devuelto.", "meta": {"difficulty": 2, "interview": true, "concepts": ["try/except/else/finally"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e3', 'm4-testing-errors', 'predict_output', 3, '{"prompt": "¿Qué imprime? Piensa qué excepción se lanza y qué cláusula la captura.", "code": "d = {''a'': 1}\ntry:\n    x = d[''b'']\nexcept (KeyError, IndexError) as e:\n    print(type(e).__name__, e)\ntry:\n    int(''12x'')\nexcept ValueError as e:\n    print(''valor:'', e)", "expected_output": "KeyError ''b''\nvalor: invalid literal for int() with base 10: ''12x''", "explanation": "Acceder a una clave inexistente lanza KeyError, cuyo mensaje es la clave con comillas. int(''12x'') no es un TypeError (el tipo es correcto, str) sino ValueError: el valor no es convertible.", "meta": {"difficulty": 2, "interview": false, "concepts": ["jerarquía de excepciones", "KeyError", "ValueError"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e4', 'm4-testing-errors', 'parsons', 4, '{"prompt": "Ordena las líneas para definir una excepción propia con un atributo extra y lanzarla desde una función de validación.", "lines": ["class EdadInvalida(ValueError):", "    def __init__(self, edad):", "        super().__init__(f''edad no válida: {edad}'')", "        self.edad = edad", "", "def validar(edad):", "    if edad < 0 or edad > 150:", "        raise EdadInvalida(edad)", "    return edad"], "meta": {"difficulty": 2, "interview": false, "concepts": ["excepciones propias"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e5', 'm4-testing-errors', 'fix_bug', 5, '{"prompt": "Esta función lee números de una lista de strings y suma los válidos. Tiene dos problemas: captura demasiado (se traga incluso Ctrl+C) y el `finally` pisa el resultado. Arréglala.", "starter_code": "def sumar_validos(valores):\n    total = 0\n    for v in valores:\n        try:\n            total += int(v)\n        except:\n            pass\n    try:\n        return total\n    finally:\n        return -1", "tests": [{"call": "sumar_validos([''1'', ''2'', ''x'', ''3''])", "expected": "6"}, {"call": "sumar_validos([])", "expected": "0"}, {"call": "sumar_validos([''10'', None, ''5''])", "expected": "15"}], "hints": ["Un except desnudo captura BaseException, incluidas KeyboardInterrupt y SystemExit. Captura solo lo que esperas.", "int(None) lanza TypeError, int(''x'') lanza ValueError: captura ambos explícitamente.", "Un return dentro de finally sobreescribe cualquier return anterior: elimina ese finally."], "solution": "def sumar_validos(valores):\n    total = 0\n    for v in valores:\n        try:\n            total += int(v)\n        except (ValueError, TypeError):\n            pass\n    return total", "meta": {"difficulty": 2, "interview": true, "concepts": ["except desnudo", "finally", "return"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e6', 'm4-testing-errors', 'fix_bug', 6, '{"prompt": "La función debe convertir a float y, si falla, lanzar un ValueError propio con el mensaje ''no es un número: <texto>'' conservando la causa original (encadenado con `from`). Ahora mismo pierde la causa y cambia el tipo de excepción. Arréglala. No toques el bloque marcado.", "starter_code": "# --- no tocar ---\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e), type(e.__cause__).__name__)\n# --- fin ---\n\ndef a_float(texto):\n    try:\n        return float(texto)\n    except ValueError:\n        raise TypeError(''no es un número'')", "tests": [{"call": "a_float(''3.5'')", "expected": "3.5"}, {"call": "captura(lambda: a_float(''abc''))", "expected": "(''ValueError'', ''no es un número: abc'', ''ValueError'')"}], "hints": ["Mantén el tipo ValueError: el que llama espera un error de valor, no de tipo.", "Incluye el texto problemático en el mensaje para que el error sea accionable.", "raise ValueError(f''no es un número: {texto}'') from e"], "solution": "# --- no tocar ---\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e), type(e.__cause__).__name__)\n# --- fin ---\n\ndef a_float(texto):\n    try:\n        return float(texto)\n    except ValueError as e:\n        raise ValueError(f''no es un número: {texto}'') from e", "meta": {"difficulty": 3, "interview": true, "concepts": ["raise from", "encadenar excepciones"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e7', 'm4-testing-errors', 'code', 7, '{"prompt": "Escribe `parsear_edad(texto)` que devuelva un int. Debe lanzar ValueError si el texto no es un entero y ValueError con el mensaje ''fuera de rango'' si no está entre 0 y 150. Los espacios alrededor se ignoran. No toques el bloque marcado.", "starter_code": "# --- no tocar ---\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e))\n# --- fin ---\n\ndef parsear_edad(texto):\n    pass", "tests": [{"call": "parsear_edad('' 42 '')", "expected": "42"}, {"call": "captura(lambda: parsear_edad(''abc''))[0]", "expected": "ValueError"}, {"call": "captura(lambda: parsear_edad(''200''))", "expected": "(''ValueError'', ''fuera de rango'')"}], "hints": ["int() ya lanza ValueError con texto no numérico: no necesitas comprobarlo a mano.", "Tras convertir, valida el rango y lanza tú mismo ValueError con el mensaje exacto.", "edad = int(texto.strip()); if not 0 <= edad <= 150: raise ValueError(''fuera de rango'')"], "solution": "# --- no tocar ---\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e))\n# --- fin ---\n\ndef parsear_edad(texto):\n    edad = int(texto.strip())\n    if not 0 <= edad <= 150:\n        raise ValueError(''fuera de rango'')\n    return edad", "meta": {"difficulty": 2, "interview": false, "concepts": ["validación", "raise"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e8', 'm4-testing-errors', 'code', 8, '{"prompt": "Invierte el rol: te dan dos implementaciones de `media(lista)`, una correcta y otra con un bug (divide por len+1). Escribe `test_media(impl)` usando `assert` de forma que FALLE con la implementación rota y PASE con la correcta. No toques el bloque marcado.", "starter_code": "# --- no tocar ---\ndef media_ok(lista):\n    return sum(lista) / len(lista)\n\ndef media_bug(lista):\n    return sum(lista) / (len(lista) + 1)\n\ndef lanza_assertion(fn):\n    try:\n        fn()\n        return False\n    except AssertionError:\n        return True\n# --- fin ---\n\ndef test_media(impl):\n    pass", "tests": [{"call": "lanza_assertion(lambda: test_media(media_bug))", "expected": "True"}, {"call": "lanza_assertion(lambda: test_media(media_ok))", "expected": "False"}], "hints": ["Un test es solo una función que llama a la implementación con datos conocidos y compara con assert.", "Elige un caso donde el bug se note: con [2, 4] la media correcta es 3.0 y la rota es 2.0.", "assert impl([2, 4]) == 3.0"], "solution": "# --- no tocar ---\ndef media_ok(lista):\n    return sum(lista) / len(lista)\n\ndef media_bug(lista):\n    return sum(lista) / (len(lista) + 1)\n\ndef lanza_assertion(fn):\n    try:\n        fn()\n        return False\n    except AssertionError:\n        return True\n# --- fin ---\n\ndef test_media(impl):\n    assert impl([2, 4]) == 3.0\n    assert impl([10]) == 10.0", "meta": {"difficulty": 3, "interview": true, "concepts": ["escribir tests", "assert"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e9', 'm4-testing-errors', 'code', 9, '{"prompt": "Escribe una clase de tests con `unittest` para la función `es_palindromo` dada: un método que compruebe un palíndromo, otro que compruebe uno que no lo es, y otro que compruebe que se ignoran mayúsculas. La clase debe llamarse `TestPalindromo`. No toques el bloque marcado.", "starter_code": "import unittest, io\n\n# --- no tocar ---\ndef es_palindromo(s):\n    s = s.lower()\n    return s == s[::-1]\n\ndef ejecutar(clase):\n    suite = unittest.TestLoader().loadTestsFromTestCase(clase)\n    r = unittest.TextTestRunner(stream=io.StringIO()).run(suite)\n    return (r.testsRun, len(r.failures) + len(r.errors))\n# --- fin ---\n\nclass TestPalindromo(unittest.TestCase):\n    pass", "tests": [{"call": "ejecutar(TestPalindromo)", "expected": "(3, 0)"}], "hints": ["Cada método de test empieza por test_ y recibe self.", "Usa self.assertTrue / self.assertFalse en vez de assert a secas: dan mejores mensajes.", "def test_ignora_mayusculas(self): self.assertTrue(es_palindromo(''Ana''))"], "solution": "import unittest, io\n\n# --- no tocar ---\ndef es_palindromo(s):\n    s = s.lower()\n    return s == s[::-1]\n\ndef ejecutar(clase):\n    suite = unittest.TestLoader().loadTestsFromTestCase(clase)\n    r = unittest.TextTestRunner(stream=io.StringIO()).run(suite)\n    return (r.testsRun, len(r.failures) + len(r.errors))\n# --- fin ---\n\nclass TestPalindromo(unittest.TestCase):\n    def test_palindromo(self):\n        self.assertTrue(es_palindromo(''oso''))\n\n    def test_no_palindromo(self):\n        self.assertFalse(es_palindromo(''hola''))\n\n    def test_ignora_mayusculas(self):\n        self.assertTrue(es_palindromo(''Ana''))", "meta": {"difficulty": 2, "interview": false, "concepts": ["unittest", "TestCase"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e10', 'm4-testing-errors', 'code', 10, '{"prompt": "Implementa un context manager `Temporizador` para usar con `with`, que registre en `self.segundos` cuánto tardó el bloque (usa `time.perf_counter()`) y que NO silencie excepciones. No toques el bloque marcado.", "starter_code": "import time\n\nclass Temporizador:\n    pass\n\n# --- no tocar ---\ndef medir():\n    with Temporizador() as t:\n        x = sum(range(1000))\n    return t.segundos >= 0\n\ndef propaga():\n    try:\n        with Temporizador():\n            raise ValueError(''boom'')\n    except ValueError:\n        return ''propagada''\n    return ''silenciada''\n# --- fin ---", "tests": [{"call": "medir()", "expected": "True"}, {"call": "propaga()", "expected": "propagada"}], "hints": ["Un context manager necesita __enter__ (devuelve self) y __exit__(self, exc_type, exc, tb).", "Guarda perf_counter() en __enter__ y calcula la diferencia en __exit__.", "Si __exit__ devuelve False (o None), la excepción se propaga. Devolver True la silenciaría."], "solution": "import time\n\nclass Temporizador:\n    def __enter__(self):\n        self._t0 = time.perf_counter()\n        return self\n\n    def __exit__(self, exc_type, exc, tb):\n        self.segundos = time.perf_counter() - self._t0\n        return False\n\n# --- no tocar ---\ndef medir():\n    with Temporizador() as t:\n        x = sum(range(1000))\n    return t.segundos >= 0\n\ndef propaga():\n    try:\n        with Temporizador():\n            raise ValueError(''boom'')\n    except ValueError:\n        return ''propagada''\n    return ''silenciada''\n# --- fin ---", "meta": {"difficulty": 3, "interview": true, "concepts": ["context manager", "__enter__/__exit__"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e11', 'm4-testing-errors', 'recall', 11, '{"prompt": "Entrevista: ¿por qué es mala práctica un `except Exception: pass` en código de producción? Da dos razones y una alternativa aceptable.", "isCode": false, "modelAnswer": "1) Oculta errores reales: el programa sigue con estado inconsistente y el fallo aparece lejos de su causa. 2) Hace imposible depurar porque no queda rastro. Alternativa: capturar solo las excepciones esperadas, y si hay que continuar, registrar el error (logging.exception) y decidir explícitamente qué hacer.", "meta": {"difficulty": 2, "interview": true, "concepts": ["manejo de errores"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e12', 'm4-testing-errors', 'recall', 12, '{"prompt": "Entrevista: en tu proyecto rag-finance evaluaste con RAGAS. ¿Qué diferencia hay entre un test unitario clásico de una función y una evaluación de un sistema con LLM? ¿Qué se puede afirmar con cada uno?", "isCode": false, "modelAnswer": "Un test unitario es determinista: misma entrada, misma salida, pasa o falla. Una evaluación de LLM es estadística: mide métricas (faithfulness, recall) sobre un conjunto de casos, y la salida varía. Con el test afirmas corrección de una unidad; con la evaluación afirmas una tendencia de calidad y detectas regresiones al cambiar prompts, chunking o modelo.", "meta": {"difficulty": 3, "interview": true, "concepts": ["testing vs evaluación", "RAGAS"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e13', 'm4-testing-errors', 'flashcard', 13, '{"prompt": "¿Qué diferencia hay entre `raise X from e` y `raise X` dentro de un except?", "answer": "from e enlaza la nueva excepción con la causa (__cause__) y el traceback muestra ''The above exception was the direct cause''. Sin from, Python solo guarda el contexto implícito.", "explanation": "Encadenar conserva la información de depuración al traducir errores de bajo nivel a errores de dominio.", "meta": {"difficulty": 2, "interview": false, "concepts": ["raise from"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e14', 'm4-testing-errors', 'flashcard', 14, '{"prompt": "¿Qué excepción lanza int(''3.5'')? ¿Y int(None)?", "answer": "int(''3.5'') lanza ValueError (tipo correcto, valor inválido). int(None) lanza TypeError (tipo no convertible).", "explanation": "ValueError = el tipo es el adecuado pero el contenido no; TypeError = el tipo en sí es incorrecto.", "meta": {"difficulty": 1, "interview": false, "concepts": ["ValueError vs TypeError"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e15', 'm4-testing-errors', 'flashcard', 15, '{"prompt": "En pytest, ¿cómo se comprueba que una función lanza una excepción?", "answer": "with pytest.raises(ValueError): funcion()", "explanation": "En unittest el equivalente es with self.assertRaises(ValueError):. pytest no está en Pyodide, pero es lo que usarás en cualquier repo real.", "meta": {"difficulty": 1, "interview": false, "concepts": ["pytest.raises"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e16', 'm4-testing-errors', 'flashcard', 16, '{"prompt": "¿Cuál es la clase base de todas las excepciones que normalmente deberías capturar?", "answer": "Exception. BaseException incluye además KeyboardInterrupt, SystemExit y GeneratorExit, que casi nunca quieres interceptar.", "explanation": "Por eso except: (desnudo) es peligroso: equivale a except BaseException.", "meta": {"difficulty": 1, "interview": true, "concepts": ["jerarquía de excepciones"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m4-e17', 'm4-testing-errors', 'flashcard', 17, '{"prompt": "¿Qué es un fixture en testing?", "answer": "Código que prepara el estado necesario para un test (datos, conexiones, ficheros temporales) y lo limpia después. En unittest: setUp/tearDown; en pytest: funciones decoradas con @pytest.fixture.", "explanation": "Evita repetir preparación en cada test y aísla los tests entre sí.", "meta": {"difficulty": 1, "interview": false, "concepts": ["fixtures"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== m5 =====
insert into exercises (id, node_id, type, position, content) values
  ('m5-e1', 'm5-async', 'recall', 1, '{"prompt": "Calentamiento (M4): ¿en qué orden se ejecutan `try`, `except`, `else` y `finally`, y cuál corre siempre?", "isCode": false, "modelAnswer": "try primero; si hay excepción, except; si no la hay, else; finally corre siempre al final, haya o no excepción e incluso si hubo return.", "meta": {"difficulty": 1, "interview": false, "concepts": ["try/except"], "recuerda_de": "m4-testing-errors"}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e2', 'm5-async', 'predict_output', 2, '{"prompt": "¿Qué imprime? Aquí las corrutinas se esperan una detrás de otra.", "code": "import asyncio\n\nasync def tarea(nombre, n):\n    print(''inicio'', nombre)\n    await asyncio.sleep(0)\n    print(''fin'', nombre)\n    return n * 2\n\nasync def main():\n    a = await tarea(''A'', 1)\n    b = await tarea(''B'', 2)\n    print(a + b)\n\nasyncio.run(main())", "expected_output": "inicio A\nfin A\ninicio B\nfin B\n6", "explanation": "await sobre una corrutina la ejecuta hasta el final antes de continuar. No hay concurrencia aquí: B no empieza hasta que A termina, aunque A haya cedido el control con sleep(0), porque nadie más estaba esperando.", "meta": {"difficulty": 2, "interview": true, "concepts": ["await secuencial"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e3', 'm5-async', 'predict_output', 3, '{"prompt": "¿Qué imprime ahora, con gather? Fíjate en cómo se intercalan los prints.", "code": "import asyncio\n\nasync def tarea(nombre, n):\n    print(''inicio'', nombre)\n    await asyncio.sleep(0)\n    print(''fin'', nombre)\n    return n * 2\n\nasync def main():\n    r = await asyncio.gather(tarea(''A'', 1), tarea(''B'', 2))\n    print(r)\n\nasyncio.run(main())", "expected_output": "inicio A\ninicio B\nfin A\nfin B\n[2, 4]", "explanation": "gather planifica ambas corrutinas. A corre hasta su primer await y cede; entonces B corre hasta el suyo; luego A reanuda y termina, y después B. gather devuelve los resultados en el orden en que se pasaron, no en el que terminaron.", "meta": {"difficulty": 2, "interview": true, "concepts": ["gather", "event loop"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e4', 'm5-async', 'predict_output', 4, '{"prompt": "¿Qué imprime? Aquí hay una trampa: una de las funciones no cede nunca el control.", "code": "import asyncio\n\nasync def bloqueante():\n    print(''bloqueante empieza'')\n    total = sum(range(100))\n    print(''bloqueante acaba'', total)\n\nasync def rapida():\n    print(''rapida'')\n\nasync def main():\n    await asyncio.gather(bloqueante(), rapida())\n\nasyncio.run(main())", "expected_output": "bloqueante empieza\nbloqueante acaba 4950\nrapida", "explanation": "async no significa paralelo. bloqueante no tiene ningún await, así que ocupa el hilo hasta terminar; rapida solo corre cuando bloqueante devuelve el control. Para CPU-bound, async no ayuda: necesitas procesos o hilos.", "meta": {"difficulty": 3, "interview": true, "concepts": ["CPU-bound", "cooperativo"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e5', 'm5-async', 'parsons', 5, '{"prompt": "Ordena las líneas para descargar (simulado) varias URLs de forma concurrente con gather.", "lines": ["import asyncio", "", "async def descargar(url):", "    await asyncio.sleep(0.01)", "    return f''contenido de {url}''", "", "async def main(urls):", "    tareas = [descargar(u) for u in urls]", "    return await asyncio.gather(*tareas)"], "meta": {"difficulty": 2, "interview": false, "concepts": ["gather", "corrutinas"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e6', 'm5-async', 'fix_bug', 6, '{"prompt": "La función debe sumar los resultados de varias corrutinas. Ahora mismo falla porque olvida esperar las corrutinas: suma objetos coroutine en vez de números. Arréglala manteniendo la concurrencia.", "starter_code": "import asyncio\n\nasync def valor(n):\n    await asyncio.sleep(0)\n    return n\n\nasync def sumar(ns):\n    resultados = [valor(n) for n in ns]\n    return sum(resultados)", "tests": [{"call": "await sumar([1, 2, 3])", "expected": "6"}, {"call": "await sumar([])", "expected": "0"}], "hints": ["Llamar a una función async devuelve una corrutina, no su resultado.", "gather acepta varias corrutinas y devuelve una lista con sus resultados cuando todas acaban.", "resultados = await asyncio.gather(*[valor(n) for n in ns])"], "solution": "import asyncio\n\nasync def valor(n):\n    await asyncio.sleep(0)\n    return n\n\nasync def sumar(ns):\n    resultados = await asyncio.gather(*[valor(n) for n in ns])\n    return sum(resultados)", "meta": {"difficulty": 2, "interview": true, "concepts": ["await olvidado", "gather"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e7', 'm5-async', 'code', 7, '{"prompt": "Escribe `async def con_timeout(coro, segundos)` que devuelva el resultado de la corrutina, o la cadena ''timeout'' si tarda más de lo indicado. Usa `asyncio.wait_for`.", "starter_code": "import asyncio\n\nasync def lenta(s):\n    await asyncio.sleep(s)\n    return ''ok''\n\nasync def con_timeout(coro, segundos):\n    pass", "tests": [{"call": "await con_timeout(lenta(0.01), 1)", "expected": "ok"}, {"call": "await con_timeout(lenta(0.2), 0.01)", "expected": "timeout"}], "hints": ["wait_for envuelve una corrutina y lanza una excepción si excede el tiempo.", "La excepción es asyncio.TimeoutError (en Python 3.11+ es alias de TimeoutError).", "try: return await asyncio.wait_for(coro, segundos) except asyncio.TimeoutError: return ''timeout''"], "solution": "import asyncio\n\nasync def lenta(s):\n    await asyncio.sleep(s)\n    return ''ok''\n\nasync def con_timeout(coro, segundos):\n    try:\n        return await asyncio.wait_for(coro, segundos)\n    except asyncio.TimeoutError:\n        return ''timeout''", "meta": {"difficulty": 2, "interview": false, "concepts": ["wait_for", "timeouts"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e8', 'm5-async', 'code', 8, '{"prompt": "Escribe `async def limitar(coros, max_conc)` que ejecute las corrutinas con como máximo `max_conc` en vuelo a la vez, usando `asyncio.Semaphore`, y devuelva la lista de resultados en orden. Este patrón es el que usas para no saturar una API de LLM con peticiones.", "starter_code": "import asyncio\n\nasync def limitar(coros, max_conc):\n    pass\n\nasync def eco(x):\n    await asyncio.sleep(0)\n    return x", "tests": [{"call": "await limitar([eco(1), eco(2), eco(3)], 2)", "expected": "[1, 2, 3]"}, {"call": "await limitar([], 5)", "expected": "[]"}], "hints": ["Un Semaphore(n) deja pasar n corrutinas a la vez; las demás esperan en acquire.", "Envuelve cada corrutina en una función interna que haga async with sem: return await coro.", "return await asyncio.gather(*[envuelta(c) for c in coros])"], "solution": "import asyncio\n\nasync def limitar(coros, max_conc):\n    sem = asyncio.Semaphore(max_conc)\n\n    async def envuelta(c):\n        async with sem:\n            return await c\n\n    return await asyncio.gather(*[envuelta(c) for c in coros])\n\nasync def eco(x):\n    await asyncio.sleep(0)\n    return x", "meta": {"difficulty": 3, "interview": true, "concepts": ["Semaphore", "rate limiting"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e9', 'm5-async', 'code', 9, '{"prompt": "Escribe `async def primero_que_falle(coros)` que ejecute las corrutinas con gather y `return_exceptions=True`, y devuelva el número de resultados que fueron excepciones.", "starter_code": "import asyncio\n\nasync def ok():\n    return 1\n\nasync def falla():\n    raise ValueError(''x'')\n\nasync def primero_que_falle(coros):\n    pass", "tests": [{"call": "await primero_que_falle([ok(), falla(), ok(), falla()])", "expected": "2"}, {"call": "await primero_que_falle([ok()])", "expected": "0"}], "hints": ["Sin return_exceptions, gather propaga la primera excepción y pierdes el resto.", "Con return_exceptions=True las excepciones aparecen como objetos en la lista de resultados.", "return sum(isinstance(r, Exception) for r in resultados)"], "solution": "import asyncio\n\nasync def ok():\n    return 1\n\nasync def falla():\n    raise ValueError(''x'')\n\nasync def primero_que_falle(coros):\n    resultados = await asyncio.gather(*coros, return_exceptions=True)\n    return sum(isinstance(r, Exception) for r in resultados)", "meta": {"difficulty": 2, "interview": false, "concepts": ["return_exceptions", "gather"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e10', 'm5-async', 'recall', 10, '{"prompt": "Entrevista: explica la diferencia entre concurrencia y paralelismo, y por qué asyncio da lo primero pero no lo segundo.", "isCode": false, "modelAnswer": "Concurrencia es gestionar varias tareas a la vez intercalándolas; paralelismo es ejecutarlas literalmente al mismo tiempo en varios núcleos. asyncio corre en un único hilo con un event loop: cuando una tarea espera E/S (await), cede el control a otra. Nunca hay dos ejecutándose a la vez, así que para CPU-bound no acelera nada; para I/O-bound (APIs, red, disco) sí, porque el tiempo de espera se aprovecha.", "meta": {"difficulty": 2, "interview": true, "concepts": ["concurrencia vs paralelismo"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e11', 'm5-async', 'recall', 11, '{"prompt": "Entrevista: en un pipeline de RAG tienes que generar embeddings de 5.000 chunks llamando a una API. ¿Cómo usarías asyncio y qué límite tendrías que respetar?", "isCode": false, "modelAnswer": "Lanzaría las llamadas concurrentemente con gather, pero limitadas con un Semaphore (p. ej. 10-20 en vuelo) para respetar el rate limit de la API, con reintentos con backoff en errores 429, y agrupando chunks en lotes si la API admite batch. El cuello de botella es la red, no la CPU, así que async encaja.", "meta": {"difficulty": 3, "interview": true, "concepts": ["async en RAG", "rate limit"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e12', 'm5-async', 'flashcard', 12, '{"prompt": "¿Qué devuelve llamar a una función definida con `async def` sin await?", "answer": "Un objeto coroutine que todavía no se ha ejecutado. Solo corre cuando se le hace await o se planifica como tarea.", "explanation": "Es el error más común: sumar, imprimir o devolver corrutinas en vez de resultados.", "meta": {"difficulty": 1, "interview": true, "concepts": ["corrutinas"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e13', 'm5-async', 'flashcard', 13, '{"prompt": "¿Diferencia entre `await coro()` y `asyncio.create_task(coro())`?", "answer": "await espera el resultado ahí mismo. create_task planifica la corrutina en el loop y devuelve un Task inmediatamente, que se ejecuta en segundo plano hasta que hagas await sobre él.", "explanation": "create_task es lo que permite lanzar algo y seguir haciendo otras cosas.", "meta": {"difficulty": 2, "interview": true, "concepts": ["create_task"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e14', 'm5-async', 'flashcard', 14, '{"prompt": "¿Qué hace `asyncio.gather(*coros)`?", "answer": "Ejecuta todas las corrutinas concurrentemente y devuelve una lista con sus resultados en el mismo orden en que se pasaron.", "explanation": "Si una falla, propaga la excepción salvo que uses return_exceptions=True.", "meta": {"difficulty": 1, "interview": false, "concepts": ["gather"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('m5-e15', 'm5-async', 'flashcard', 15, '{"prompt": "¿Por qué `time.sleep(1)` dentro de una corrutina es un error?", "answer": "Porque bloquea el hilo entero y ningún otra tarea puede avanzar. Hay que usar await asyncio.sleep(1).", "explanation": "Cualquier llamada bloqueante (requests, time.sleep, cálculos largos) congela el event loop.", "meta": {"difficulty": 1, "interview": true, "concepts": ["bloqueo del loop"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
