-- Seed de contenido — side quests S1–S6
-- Generado por gen.py; cada bloque JSONB validado ejecutándolo.
-- Idempotente: on conflict (id) do update.

-- ===== s1 =====
insert into exercises (id, node_id, type, position, content) values
  ('s1-e1', 's1-clean-code', 'predict_output', 1, '{"prompt": "Dos versiones del mismo cálculo. ¿Qué imprime? Y después pregúntate cuál entenderías dentro de seis meses.", "code": "def f(l, t):\n    r = 0\n    for x in l:\n        if x > t:\n            r += x\n    return r\n\ndef suma_mayores_que(valores, umbral):\n    return sum(v for v in valores if v > umbral)\n\nprint(f([1, 5, 10], 4), suma_mayores_que([1, 5, 10], 4))", "expected_output": "15 15", "explanation": "Hacen lo mismo. La segunda se lee como una frase: nombres que dicen qué son, sin estado intermedio, sin necesitar comentarios. La legibilidad no cambia el resultado, cambia el coste de mantenerlo.", "meta": {"difficulty": 1, "interview": false, "concepts": ["nombres", "legibilidad"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e2', 's1-clean-code', 'fix_bug', 2, '{"prompt": "Este código funciona y pasa los tests. El ''bug'' es de legibilidad: nombres crípticos, número mágico y una condición negada doble. Refactoriza sin cambiar el comportamiento: la función debe llamarse `aplicar_descuento`, recibir `precio` y `es_socio`, y usar una constante `DESCUENTO_SOCIO = 0.1`.", "starter_code": "def ad(p, s):\n    if not (not s):\n        return p - p * 0.1\n    return p\n\ndef aplicar_descuento(precio, es_socio):\n    return ad(precio, es_socio)", "tests": [{"call": "aplicar_descuento(100, True)", "expected": "90.0"}, {"call": "aplicar_descuento(100, False)", "expected": "100"}, {"call": "DESCUENTO_SOCIO", "expected": "0.1"}, {"call": "''ad'' in globals()", "expected": "False"}], "hints": ["Elimina la función intermedia: una sola función con nombres que expliquen la intención.", "Sustituye 0.1 por una constante con nombre en mayúsculas a nivel de módulo.", "if es_socio: return precio * (1 - DESCUENTO_SOCIO)"], "solution": "DESCUENTO_SOCIO = 0.1\n\ndef aplicar_descuento(precio, es_socio):\n    if es_socio:\n        return precio - precio * DESCUENTO_SOCIO\n    return precio", "meta": {"difficulty": 2, "interview": true, "concepts": ["refactor", "números mágicos", "nombres"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e3', 's1-clean-code', 'match', 3, '{"prompt": "Une cada ''olor'' de código con el principio de Clean Code que lo corrige.", "pairs": [{"term": "Función de 80 líneas que valida, calcula y guarda", "definition": "Una función hace una sola cosa (single level of abstraction)"}, {"term": "if x == 7 sin explicación", "definition": "Números mágicos: sustituir por constantes con nombre"}, {"term": "# incrementa i en 1 encima de i += 1", "definition": "El comentario no aporta: el código ya lo dice; comenta el porqué, no el qué"}, {"term": "El mismo bloque copiado en tres sitios", "definition": "DRY: extraer a una función"}, {"term": "Función con 7 parámetros", "definition": "Agrupar en un objeto o dataclass; demasiados parámetros ocultan una abstracción"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["code smells"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e4', 's1-clean-code', 'recall', 4, '{"prompt": "Entrevista: ¿cuándo SÍ escribes un comentario en el código? Da dos casos legítimos y uno en el que el comentario indica un problema de diseño.", "isCode": false, "modelAnswer": "Legítimos: explicar un porqué no evidente (una decisión de negocio, un workaround por un bug de una librería) y advertir de consecuencias (rendimiento, orden de llamada). Señal de problema: un comentario que explica qué hace un bloque de código; eso pide extraer el bloque a una función con ese nombre.", "meta": {"difficulty": 2, "interview": true, "concepts": ["comentarios"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e5', 's1-clean-code', 'recall', 5, '{"prompt": "Escribe de memoria una función `es_mayor_de_edad(fecha_nacimiento, hoy)` con nombres claros y sin números mágicos, usando una constante `MAYORIA_DE_EDAD = 18`. Solo la estructura, sin librerías de fechas: asume que recibes años como enteros.", "isCode": true, "modelAnswer": "MAYORIA_DE_EDAD = 18\n\ndef es_mayor_de_edad(anio_nacimiento, anio_actual):\n    edad = anio_actual - anio_nacimiento\n    return edad >= MAYORIA_DE_EDAD", "meta": {"difficulty": 1, "interview": false, "concepts": ["constantes", "nombres"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e6', 's1-clean-code', 'flashcard', 6, '{"prompt": "¿Qué dice la regla del boy scout aplicada al código?", "answer": "Deja el código un poco mejor de como lo encontraste: un nombre mejor, una función extraída, un comentario obsoleto borrado.", "explanation": "Mejora incremental en cada PR en vez de grandes refactors que nunca llegan.", "meta": {"difficulty": 1, "interview": false, "concepts": ["boy scout rule"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e7', 's1-clean-code', 'flashcard', 7, '{"prompt": "¿Qué es un nombre ''con intención'' (intention-revealing)?", "answer": "Uno que responde qué es, por qué existe y cómo se usa sin necesitar un comentario: dias_desde_ultimo_pago en vez de d.", "explanation": "El coste de leer un nombre largo es menor que el de descifrar uno corto.", "meta": {"difficulty": 1, "interview": false, "concepts": ["nombres"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s1-e8', 's1-clean-code', 'flashcard', 8, '{"prompt": "¿Qué es DRY y cuál es su trampa?", "answer": "Don''t Repeat Yourself: cada pieza de conocimiento en un solo sitio. Trampa: unificar código que solo se parece por casualidad crea acoplamiento; duplicar dos veces es aceptable, abstraer a la tercera.", "explanation": "La duplicación de conocimiento es el problema, no la de líneas.", "meta": {"difficulty": 2, "interview": true, "concepts": ["DRY"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== s2 =====
insert into exercises (id, node_id, type, position, content) values
  ('s2-e1', 's2-solid', 'recall', 1, '{"prompt": "Calentamiento (M3): ¿qué diferencia hay entre herencia y composición? Da un ejemplo de cada una en una frase.", "isCode": false, "modelAnswer": "Herencia: ''es un'' (Gato es un Animal, hereda comportamiento). Composición: ''tiene un'' (Coche tiene un Motor, delega en él). La composición acopla menos y se puede cambiar en tiempo de ejecución.", "meta": {"difficulty": 1, "interview": true, "concepts": ["herencia vs composición"], "recuerda_de": "m3-oop"}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e2', 's2-solid', 'match', 2, '{"prompt": "Une cada principio SOLID con su formulación práctica.", "pairs": [{"term": "S — Responsabilidad única", "definition": "Una clase tiene una sola razón para cambiar"}, {"term": "O — Abierto/cerrado", "definition": "Añadir comportamiento nuevo sin modificar código existente (extender, no editar)"}, {"term": "L — Sustitución de Liskov", "definition": "Cualquier subclase puede usarse donde se espera la clase base sin romper nada"}, {"term": "I — Segregación de interfaces", "definition": "Mejor varias interfaces pequeñas que una grande que obliga a implementar lo que no usas"}, {"term": "D — Inversión de dependencias", "definition": "Depender de abstracciones (protocolos) y no de implementaciones concretas"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["SOLID"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e3', 's2-solid', 'predict_output', 3, '{"prompt": "Violación de Liskov. ¿Qué imprime? Piensa por qué el segundo caso ''sorprende'' a quien usa la clase base.", "code": "class Rectangulo:\n    def __init__(self, ancho, alto):\n        self.ancho, self.alto = ancho, alto\n    def set_ancho(self, a):\n        self.ancho = a\n    def area(self):\n        return self.ancho * self.alto\n\nclass Cuadrado(Rectangulo):\n    def set_ancho(self, a):\n        self.ancho = self.alto = a\n\ndef doblar_ancho(r):\n    r.set_ancho(r.ancho * 2)\n    return r.area()\n\nprint(doblar_ancho(Rectangulo(2, 3)))\nprint(doblar_ancho(Cuadrado(2, 2)))", "expected_output": "12\n16", "explanation": "Quien escribió doblar_ancho espera que cambiar el ancho no toque el alto: con Rectangulo(2,3) obtiene 4*3=12. Cuadrado rompe esa expectativa (4*4=16). Cuadrado ''es un'' rectángulo en matemáticas pero no como subtipo sustituible.", "meta": {"difficulty": 3, "interview": true, "concepts": ["Liskov"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e4', 's2-solid', 'code', 4, '{"prompt": "Inversión de dependencias. `Notificador` está acoplado a `EmailReal`. Refactoriza para que reciba en el constructor cualquier objeto con un método `enviar(destino, texto)` y devuelva lo que ese método devuelva. Así se puede testear con un doble. No toques el bloque marcado.", "starter_code": "# --- no tocar ---\nclass EmailReal:\n    def enviar(self, destino, texto):\n        return f''email a {destino}''\n\nclass Fake:\n    def __init__(self):\n        self.enviados = []\n    def enviar(self, destino, texto):\n        self.enviados.append((destino, texto))\n        return ''fake''\n# --- fin ---\n\nclass Notificador:\n    def __init__(self):\n        self.canal = EmailReal()\n\n    def avisar(self, usuario, texto):\n        return self.canal.enviar(usuario, texto)", "tests": [{"call": "Notificador(EmailReal()).avisar(''ana'', ''hola'')", "expected": "email a ana"}, {"call": "f = Fake(); n = Notificador(f); n.avisar(''bob'', ''hey''); f.enviados", "expected": "[(''bob'', ''hey'')]"}], "hints": ["El constructor debe recibir el canal como parámetro en vez de crearlo dentro.", "En Python no necesitas una interfaz formal: basta con que el objeto tenga el método (duck typing).", "def __init__(self, canal): self.canal = canal"], "solution": "# --- no tocar ---\nclass EmailReal:\n    def enviar(self, destino, texto):\n        return f''email a {destino}''\n\nclass Fake:\n    def __init__(self):\n        self.enviados = []\n    def enviar(self, destino, texto):\n        self.enviados.append((destino, texto))\n        return ''fake''\n# --- fin ---\n\nclass Notificador:\n    def __init__(self, canal):\n        self.canal = canal\n\n    def avisar(self, usuario, texto):\n        return self.canal.enviar(usuario, texto)", "meta": {"difficulty": 2, "interview": true, "concepts": ["inversión de dependencias", "inyección"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e5', 's2-solid', 'recall', 5, '{"prompt": "Entrevista: esta clase carga un CSV, calcula estadísticas y genera un PDF con el informe. ¿Qué principio viola y en cuántas clases la partirías? Nómbralas.", "isCode": false, "modelAnswer": "Viola responsabilidad única: tiene tres razones para cambiar (formato de entrada, lógica de cálculo, formato de salida). La partiría en tres: LectorCSV (o una función cargar), CalculadoraEstadisticas (lógica pura, testeable sin ficheros) y GeneradorPDF. Un orquestador pequeño las conecta.", "meta": {"difficulty": 2, "interview": true, "concepts": ["SRP"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e6', 's2-solid', 'flashcard', 6, '{"prompt": "¿Cómo se expresa una ''interfaz'' en Python moderno sin herencia?", "answer": "Con typing.Protocol: defines los métodos esperados y cualquier clase que los tenga cumple, sin heredar (structural subtyping).", "explanation": "Es duck typing con comprobación estática opcional de mypy.", "meta": {"difficulty": 2, "interview": true, "concepts": ["Protocol"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e7', 's2-solid', 'flashcard', 7, '{"prompt": "¿Cuál es la señal más clara de que violas Abierto/Cerrado?", "answer": "Cada nueva variante te obliga a añadir otro elif a la misma función (if tipo == ''pdf'' ... elif tipo == ''csv'' ...).", "explanation": "La solución suele ser polimorfismo: un objeto por variante con el mismo método, o un dict de estrategias.", "meta": {"difficulty": 2, "interview": false, "concepts": ["OCP"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s2-e8', 's2-solid', 'flashcard', 8, '{"prompt": "¿Por qué la inyección de dependencias facilita los tests?", "answer": "Porque puedes pasar un doble (fake, stub, mock) en lugar de la implementación real: sin red, sin base de datos, tests rápidos y deterministas.", "explanation": "Es el mismo principio que usaste al pasar el canal al Notificador.", "meta": {"difficulty": 1, "interview": true, "concepts": ["DI y testing"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== s3 =====
insert into exercises (id, node_id, type, position, content) values
  ('s3-e1', 's3-testing-types', 'recall', 1, '{"prompt": "Calentamiento (M4): ¿qué diferencia hay entre un fallo (failure) y un error en un test de unittest?", "isCode": false, "modelAnswer": "Fallo: el test corrió y una aserción no se cumplió (el código hace algo distinto de lo esperado). Error: el test no pudo completarse porque saltó una excepción inesperada (bug o test mal escrito).", "meta": {"difficulty": 1, "interview": false, "concepts": ["failure vs error"], "recuerda_de": "m4-testing-errors"}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e2', 's3-testing-types', 'match', 2, '{"prompt": "Une cada nivel de la pirámide de tests con lo que verifica y cuántos debería haber.", "pairs": [{"term": "Unitarios", "definition": "Una función o clase aislada, con dobles para todo lo externo; muchos y rápidos (ms)"}, {"term": "De integración", "definition": "Varias piezas juntas (código + BD real, código + API); menos, más lentos"}, {"term": "End-to-end", "definition": "El sistema completo como lo usa un usuario; muy pocos, lentos y frágiles"}, {"term": "De contrato", "definition": "Que la forma de una respuesta (esquema JSON) no cambie sin avisar a los consumidores"}, {"term": "Evaluación de LLM", "definition": "Métricas estadísticas sobre un dataset fijo; no pasa/falla, sino mejora/empeora"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["pirámide de tests"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e3', 's3-testing-types', 'match', 3, '{"prompt": "Dobles de test: une cada tipo con su definición.", "pairs": [{"term": "Stub", "definition": "Devuelve respuestas fijas; no le importa cómo lo llaman"}, {"term": "Mock", "definition": "Registra las llamadas y permite afirmar que se llamó con ciertos argumentos"}, {"term": "Fake", "definition": "Implementación funcional simplificada (una BD en memoria)"}, {"term": "Spy", "definition": "Envuelve el objeto real y registra lo que pasa sin cambiar su comportamiento"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["dobles de test"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e4', 's3-testing-types', 'code', 4, '{"prompt": "Escribe un fake para testear sin red: `class ClienteLLMFake` (no toques el bloque marcado) con `__init__(self, respuestas)` (lista) y `completar(self, prompt)` que devuelva las respuestas en orden y registre cada prompt en `self.prompts`. Al agotar las respuestas, lanza RuntimeError(''sin respuestas'').", "starter_code": "# --- no tocar ---\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return str(e)\n# --- fin ---\n\nclass ClienteLLMFake:\n    pass", "tests": [{"call": "c = ClienteLLMFake([''a'', ''b'']); c.completar(''p1''); c.completar(''p2'')", "expected": "b"}, {"call": "c = ClienteLLMFake([''a'']); c.completar(''p1''); c.prompts", "expected": "[''p1'']"}, {"call": "c = ClienteLLMFake([]); captura(lambda: c.completar(''x''))", "expected": "sin respuestas"}], "hints": ["Guarda una copia de la lista y un índice, o usa pop(0).", "Registra el prompt antes de comprobar si quedan respuestas.", "if not self.respuestas: raise RuntimeError(''sin respuestas'')"], "solution": "# --- no tocar ---\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return str(e)\n# --- fin ---\n\nclass ClienteLLMFake:\n    def __init__(self, respuestas):\n        self.respuestas = list(respuestas)\n        self.prompts = []\n\n    def completar(self, prompt):\n        self.prompts.append(prompt)\n        if not self.respuestas:\n            raise RuntimeError(''sin respuestas'')\n        return self.respuestas.pop(0)", "meta": {"difficulty": 2, "interview": true, "concepts": ["fake", "testear código con LLM"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e5', 's3-testing-types', 'recall', 5, '{"prompt": "Entrevista: ¿cómo testeas un pipeline RAG sin llamar a la API del LLM en cada test? Describe qué se testea con dobles y qué necesita el modelo real.", "isCode": false, "modelAnswer": "Con dobles: chunking, retrieval (índice pequeño en memoria con embeddings fijos), construcción del prompt, parseo de la respuesta, lógica del agente (con un cliente LLM fake que devuelve respuestas guionizadas). Con modelo real: solo la evaluación end-to-end con el dataset fijo (RAGAS), que se corre aparte, menos veces y con resultados que se comparan entre versiones, no pasa/falla.", "meta": {"difficulty": 3, "interview": true, "concepts": ["testing de RAG"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e6', 's3-testing-types', 'flashcard', 6, '{"prompt": "¿Qué es un test flaky y cuál es su causa más común?", "answer": "Uno que a veces pasa y a veces falla sin cambiar el código. Causas típicas: dependencia del tiempo, del orden de ejecución, de la red o de estado compartido entre tests.", "explanation": "Un test flaky es peor que ninguno: acaba ignorándose y esconde fallos reales.", "meta": {"difficulty": 1, "interview": true, "concepts": ["flaky"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e7', 's3-testing-types', 'flashcard', 7, '{"prompt": "¿Qué mide la cobertura de código y qué NO garantiza?", "answer": "Qué porcentaje de líneas se ejecutó durante los tests. No garantiza que las aserciones sean buenas: puedes tener 100% de cobertura sin comprobar nada.", "explanation": "Cobertura baja es una alarma; cobertura alta no es una prueba de calidad.", "meta": {"difficulty": 1, "interview": true, "concepts": ["cobertura"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s3-e8', 's3-testing-types', 'flashcard', 8, '{"prompt": "¿Qué es TDD en tres pasos?", "answer": "Rojo: escribir un test que falla. Verde: el mínimo código para que pase. Refactor: limpiar manteniendo el verde.", "explanation": "El ciclo fuerza a diseñar la interfaz antes de la implementación.", "meta": {"difficulty": 1, "interview": false, "concepts": ["TDD"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== s4 =====
insert into exercises (id, node_id, type, position, content) values
  ('s4-e1', 's4-design-patterns', 'parsons', 1, '{"prompt": "Strategy en Python idiomático: sin jerarquía de clases, las estrategias son funciones en un dict. Ordena las líneas.", "lines": ["def por_precio(items):", "    return sorted(items, key=lambda i: i[''precio''])", "", "def por_nombre(items):", "    return sorted(items, key=lambda i: i[''nombre''])", "", "ESTRATEGIAS = {''precio'': por_precio, ''nombre'': por_nombre}", "", "def ordenar(items, criterio):", "    return ESTRATEGIAS[criterio](items)"], "meta": {"difficulty": 2, "interview": true, "concepts": ["Strategy", "funciones como objetos"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e2', 's4-design-patterns', 'code', 2, '{"prompt": "Factory: escribe `crear_retriever(tipo, **kwargs)` que devuelva una instancia de `Lexico` o `Vectorial` según tipo (''lexico''/''vectorial''), pasando kwargs al constructor, y lance ValueError(f''tipo desconocido: {tipo}'') en otro caso. Usa un dict de clases, no una cadena de ifs. No toques el bloque marcado.", "starter_code": "# --- no tocar ---\nclass Lexico:\n    def __init__(self, k=5):\n        self.k = k\n\nclass Vectorial:\n    def __init__(self, k=5, modelo=''mini''):\n        self.k, self.modelo = k, modelo\n\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return str(e)\n# --- fin ---\n\ndef crear_retriever(tipo, **kwargs):\n    pass", "tests": [{"call": "r = crear_retriever(''vectorial'', k=3, modelo=''large''); (type(r).__name__, r.k, r.modelo)", "expected": "(''Vectorial'', 3, ''large'')"}, {"call": "type(crear_retriever(''lexico'')).__name__", "expected": "Lexico"}, {"call": "captura(lambda: crear_retriever(''grafo''))", "expected": "tipo desconocido: grafo"}], "hints": ["Las clases son objetos: puedes guardarlas en un dict {''lexico'': Lexico, ...}.", "Busca con .get y comprueba None para lanzar el error.", "return clase(**kwargs)"], "solution": "# --- no tocar ---\nclass Lexico:\n    def __init__(self, k=5):\n        self.k = k\n\nclass Vectorial:\n    def __init__(self, k=5, modelo=''mini''):\n        self.k, self.modelo = k, modelo\n\ndef captura(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return str(e)\n# --- fin ---\n\nTIPOS = {''lexico'': Lexico, ''vectorial'': Vectorial}\n\ndef crear_retriever(tipo, **kwargs):\n    clase = TIPOS.get(tipo)\n    if clase is None:\n        raise ValueError(f''tipo desconocido: {tipo}'')\n    return clase(**kwargs)", "meta": {"difficulty": 2, "interview": true, "concepts": ["Factory"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e3', 's4-design-patterns', 'predict_output', 3, '{"prompt": "Decorator (el patrón, implementado con el decorador de Python). ¿Qué imprime?", "code": "def con_cache(fn):\n    cache = {}\n    def envuelta(x):\n        if x not in cache:\n            print(''calculando'', x)\n            cache[x] = fn(x)\n        return cache[x]\n    return envuelta\n\n@con_cache\ndef cuadrado(x):\n    return x * x\n\nprint(cuadrado(3))\nprint(cuadrado(3))\nprint(cuadrado(4))", "expected_output": "calculando 3\n9\n9\ncalculando 4\n16", "explanation": "El decorador envuelve la función y añade comportamiento (cache) sin tocarla. La segunda llamada con 3 no imprime ''calculando'' porque ya está en cache. functools.lru_cache hace exactamente esto.", "meta": {"difficulty": 2, "interview": true, "concepts": ["Decorator", "cache"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e4', 's4-design-patterns', 'match', 4, '{"prompt": "Une cada patrón con el problema que resuelve en un sistema de IA.", "pairs": [{"term": "Strategy", "definition": "Cambiar el algoritmo de chunking o de retrieval sin tocar el pipeline"}, {"term": "Factory", "definition": "Crear el cliente de LLM adecuado (OpenAI, Gemini, local) a partir de la configuración"}, {"term": "Adapter", "definition": "Dar a dos APIs de LLM con firmas distintas una interfaz común"}, {"term": "Decorator", "definition": "Añadir reintentos, cache o logging a una llamada sin modificarla"}, {"term": "Observer", "definition": "Notificar a varios componentes (métricas, logs, UI) cada vez que el agente da un paso"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["patrones en IA"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e5', 's4-design-patterns', 'recall', 5, '{"prompt": "Entrevista: en Python muchos patrones clásicos (Strategy, Command, Singleton) son ''más simples'' que en Java. ¿Por qué? Da dos razones con ejemplo.", "isCode": false, "modelAnswer": "1) Las funciones son objetos de primera clase: una Strategy es una función en un dict, sin interfaz ni clase por variante. 2) El duck typing elimina interfaces formales: un Adapter es cualquier objeto con el método esperado. Además los módulos ya son singletons naturales, y los decoradores del lenguaje implementan el patrón Decorator directamente.", "meta": {"difficulty": 3, "interview": true, "concepts": ["patrones idiomáticos"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e6', 's4-design-patterns', 'flashcard', 6, '{"prompt": "¿Qué es el patrón Adapter?", "answer": "Una clase que traduce la interfaz de un objeto existente a la que espera tu código, para no acoplarte a la API externa.", "explanation": "Es lo que haces al envolver el SDK de cada proveedor de LLM tras un método completar(prompt) común.", "meta": {"difficulty": 1, "interview": true, "concepts": ["Adapter"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e7', 's4-design-patterns', 'flashcard', 7, '{"prompt": "¿Por qué Singleton se considera un anti-patrón en muchos casos?", "answer": "Introduce estado global oculto, dificulta los tests (no puedes sustituirlo) y acopla todo lo que lo usa.", "explanation": "En Python, una instancia a nivel de módulo inyectada como dependencia da lo mismo sin los inconvenientes.", "meta": {"difficulty": 2, "interview": true, "concepts": ["Singleton"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s4-e8', 's4-design-patterns', 'flashcard', 8, '{"prompt": "¿Qué patrón implementa functools.lru_cache?", "answer": "Decorator: envuelve la función añadiendo memoización sin cambiar su código.", "explanation": "Un decorador de Python es el patrón Decorator con sintaxis del lenguaje.", "meta": {"difficulty": 1, "interview": false, "concepts": ["lru_cache"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== s5 =====
insert into exercises (id, node_id, type, position, content) values
  ('s5-e1', 's5-architecture', 'match', 1, '{"prompt": "Arquitectura de PyQuest: une cada componente con su responsabilidad.", "pairs": [{"term": "Next.js en Vercel", "definition": "Interfaz, rutas y renderizado; habla con Supabase directamente para el progreso"}, {"term": "Supabase (Postgres + Auth + RLS)", "definition": "Datos, identidad y la regla de que cada usuario solo ve sus filas"}, {"term": "FastAPI en Render", "definition": "Solo el tutor: llama al LLM con rate limit por usuario, verificando el JWT"}, {"term": "Pyodide", "definition": "Ejecuta el código del alumno en el navegador, sin sandbox en servidor"}, {"term": "JWT de Supabase Auth", "definition": "La credencial única que tanto Supabase (RLS) como FastAPI verifican"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["arquitectura de PyQuest"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e2', 's5-architecture', 'recall', 2, '{"prompt": "Decisión de diseño: en PyQuest el cliente escribe su progreso directamente en Supabase protegido por RLS, sin pasar por FastAPI. ¿Qué gana y qué riesgo asume? ¿Cuándo dejaría de ser buena idea?", "isCode": false, "modelAnswer": "Gana: menos latencia, menos código, sin cold starts de Render en cada acción, y la autorización vive en la BD. Riesgo: cualquier regla de negocio (p. ej. ''no puedes marcar completado sin intentos'') hay que expresarla en SQL/RLS o triggers, o un cliente modificado puede saltársela. Dejaría de ser buena idea si el progreso afectara a algo con valor real (ranking público, certificados): entonces la validación pasaría al backend.", "meta": {"difficulty": 3, "interview": true, "concepts": ["RLS", "confianza en el cliente"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e3', 's5-architecture', 'recall', 3, '{"prompt": "Decisión de diseño: el estado ''available'' de un nodo se calcula en cada carga a partir de los intentos, nunca se guarda. Explica el fallo que esto evita y el coste que tiene.", "isCode": false, "modelAnswer": "Evita estado derivado obsoleto: si se guardara, añadir ejercicios a un nodo ya completado o cambiar prerrequisitos dejaría datos incoherentes que habría que migrar. Al derivarlo de la fuente de verdad (los intentos), añadir contenido nunca corrompe progreso. Coste: cómputo en cada carga; irrelevante con 15 nodos, y si creciera se cachearía, no se persistiría.", "meta": {"difficulty": 3, "interview": true, "concepts": ["estado derivado", "fuente de verdad"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e4', 's5-architecture', 'recall', 4, '{"prompt": "Decisión de diseño: exercise_attempts es un log de eventos (se añade, no se edita) y no una tabla de ''estado actual del ejercicio''. ¿Qué te permite hacer ese diseño que el otro no?", "isCode": false, "modelAnswer": "Reconstruir cualquier vista a posteriori: ''repasa tus errores'', estadísticas por concepto, racha, o una métrica nueva que no existía cuando se guardó el dato. Con estado actual solo tienes la última foto y pierdes la historia. Es event sourcing en pequeño.", "meta": {"difficulty": 2, "interview": true, "concepts": ["event log", "event sourcing"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e5', 's5-architecture', 'predict_output', 5, '{"prompt": "Cálculo del estado de un nodo (simplificado). ¿Qué imprime?", "code": "prereqs = {''m1'': [], ''m2'': [''m1''], ''m3'': [''m2''], ''s1'': [''m1'']}\ncompletados = {''m1''}\n\ndef estado(n):\n    if n in completados:\n        return ''completed''\n    if all(p in completados for p in prereqs[n]):\n        return ''available''\n    return ''locked''\n\nfor n in [''m1'', ''m2'', ''m3'', ''s1'']:\n    print(n, estado(n))", "expected_output": "m1 completed\nm2 available\nm3 locked\ns1 available", "explanation": "m2 y s1 dependen solo de m1, que está completado, así que están disponibles. m3 depende de m2, aún no completado: bloqueado. all([]) es True, por eso m1 sin prerrequisitos siempre está al menos disponible.", "meta": {"difficulty": 1, "interview": false, "concepts": ["estado derivado", "prerrequisitos"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e6', 's5-architecture', 'flashcard', 6, '{"prompt": "¿Qué es un monolito modular y por qué suele ser mejor punto de partida que microservicios?", "answer": "Una sola aplicación desplegable con módulos bien separados internamente. Evita la complejidad operativa de red, despliegues múltiples y datos distribuidos hasta que haya una razón real (equipos, escala) para partirlo.", "explanation": "PyQuest es dos servicios solo porque Pyodide+Next y el tutor Python tienen requisitos distintos, no por moda.", "meta": {"difficulty": 2, "interview": true, "concepts": ["monolito modular"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e7', 's5-architecture', 'flashcard', 7, '{"prompt": "¿Qué son los 12 factores (12-factor app) en una frase?", "answer": "Un conjunto de prácticas para apps desplegables en la nube: configuración en variables de entorno, dependencias declaradas, procesos sin estado, logs como flujo, paridad dev/prod.", "explanation": "Vercel y Render asumen estas prácticas; por eso la config de PyQuest va en variables de entorno.", "meta": {"difficulty": 1, "interview": false, "concepts": ["12-factor"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s5-e8', 's5-architecture', 'flashcard', 8, '{"prompt": "¿Qué es un ADR (Architecture Decision Record)?", "answer": "Un documento corto por decisión: contexto, opciones consideradas, decisión y consecuencias. Se guarda en el repo.", "explanation": "Tu status.md de PyQuest ya contiene ADRs implícitos (''reglas de diseño, no relitigar''); formalizarlos es barato y da mucho en entrevistas.", "meta": {"difficulty": 1, "interview": true, "concepts": ["ADR"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;

-- ===== s6 =====
insert into exercises (id, node_id, type, position, content) values
  ('s6-e1', 's6-docker', 'parsons', 1, '{"prompt": "Ordena las líneas de este Dockerfile para una API FastAPI. Pista: el orden afecta a la caché de capas, así que las dependencias van antes que el código.", "lang": "dockerfile", "lines": ["FROM python:3.12-slim", "WORKDIR /app", "COPY requirements.txt .", "RUN pip install --no-cache-dir -r requirements.txt", "COPY . .", "EXPOSE 8000", "CMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]"], "meta": {"difficulty": 2, "interview": true, "concepts": ["Dockerfile", "caché de capas"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e2', 's6-docker', 'predict_output', 2, '{"prompt": "Simulación de la caché de capas de Docker. ¿Qué imprime? Cada capa se reconstruye si cambia su contenido o si cambió alguna anterior.", "code": "capas = [''FROM'', ''COPY requirements'', ''RUN pip install'', ''COPY codigo'']\ncambiado = {''COPY codigo''}\n\ninvalidada = False\nfor capa in capas:\n    if capa in cambiado:\n        invalidada = True\n    print(capa, ''cache'' if not invalidada else ''rebuild'')", "expected_output": "FROM cache\nCOPY requirements cache\nRUN pip install cache\nCOPY codigo rebuild", "explanation": "Solo cambió el código, que está en la última capa: pip install se reutiliza de caché. Si COPY del código estuviera antes que requirements, cada cambio de una línea de código reinstalaría todas las dependencias.", "meta": {"difficulty": 2, "interview": true, "concepts": ["caché de capas"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e3', 's6-docker', 'match', 3, '{"prompt": "Une cada instrucción o concepto de Docker con su significado.", "pairs": [{"term": "FROM", "definition": "Imagen base de la que parte la tuya"}, {"term": "COPY vs volumen", "definition": "COPY mete ficheros en la imagen al construir; un volumen los monta en tiempo de ejecución"}, {"term": "CMD vs ENTRYPOINT", "definition": "CMD es el comando por defecto (sustituible); ENTRYPOINT es fijo y CMD le pasa argumentos"}, {"term": "EXPOSE", "definition": "Documenta el puerto; no lo publica (eso lo hace -p al ejecutar)"}, {"term": ".dockerignore", "definition": "Excluye ficheros del contexto de build (.git, venv, .env) para imágenes más pequeñas y seguras"}], "meta": {"difficulty": 2, "interview": true, "concepts": ["instrucciones Docker"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e4', 's6-docker', 'recall', 4, '{"prompt": "Entrevista: explica la diferencia entre imagen y contenedor con una analogía, y qué pasa con los datos escritos dentro de un contenedor cuando se elimina.", "isCode": false, "modelAnswer": "La imagen es la plantilla inmutable (como una clase); el contenedor es una instancia en ejecución con su capa de escritura. Los datos escritos en esa capa se pierden al eliminar el contenedor; para persistir se usan volúmenes o servicios externos (la BD de PyQuest vive en Supabase, no en el contenedor).", "meta": {"difficulty": 2, "interview": true, "concepts": ["imagen vs contenedor", "persistencia"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e5', 's6-docker', 'recall', 5, '{"prompt": "Escribe de memoria un docker-compose mínimo con dos servicios: `api` (build del directorio actual, puerto 8000:8000, variable de entorno LLM_API_KEY tomada del host) y `db` (imagen postgres:16, con un volumen para los datos).", "isCode": true, "modelAnswer": "services:\n  api:\n    build: .\n    ports:\n      - \"8000:8000\"\n    environment:\n      - LLM_API_KEY=${LLM_API_KEY}\n    depends_on:\n      - db\n  db:\n    image: postgres:16\n    volumes:\n      - pgdata:/var/lib/postgresql/data\nvolumes:\n  pgdata:", "meta": {"difficulty": 2, "interview": false, "concepts": ["docker compose"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e6', 's6-docker', 'flashcard', 6, '{"prompt": "¿Por qué usar python:3.12-slim en vez de python:3.12?", "answer": "Es mucho más pequeña (menos herramientas del sistema), así que la imagen se construye, sube y arranca más rápido y tiene menos superficie de ataque.", "explanation": "alpine es aún menor pero usa musl y da problemas con paquetes con binarios (numpy).", "meta": {"difficulty": 1, "interview": false, "concepts": ["imágenes base"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e7', 's6-docker', 'flashcard', 7, '{"prompt": "¿Cómo se pasan secretos a un contenedor sin meterlos en la imagen?", "answer": "Con variables de entorno en tiempo de ejecución (-e, env_file, o el gestor de secretos de la plataforma), nunca con COPY .env ni hardcodeados en el Dockerfile.", "explanation": "Todo lo que va en una capa de imagen queda en el historial aunque lo borres después.", "meta": {"difficulty": 2, "interview": true, "concepts": ["secretos"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
insert into exercises (id, node_id, type, position, content) values
  ('s6-e8', 's6-docker', 'flashcard', 8, '{"prompt": "¿Qué es un build multi-stage y para qué sirve?", "answer": "Un Dockerfile con varias etapas FROM: una compila o instala dependencias y otra copia solo el resultado, dejando fuera compiladores y caches.", "explanation": "Imágenes finales más pequeñas y sin herramientas de build en producción.", "meta": {"difficulty": 2, "interview": true, "concepts": ["multi-stage"]}}'::jsonb)
  on conflict (id) do update set node_id=excluded.node_id, type=excluded.type, position=excluded.position, content=excluded.content;
