-- English migration, step 3: M4-M5 exercises + lessons content + lesson titles. Idempotent.

update exercises set content = '{"isCode": false, "prompt": "Warm-up (M3): explain in your own words what `super().__init__()` does inside a child class''s constructor, and what would happen if you omitted it.", "modelAnswer": "It calls the parent class''s constructor so it can initialize its own attributes. If you omit it, the attributes the parent defines in its __init__ don''t exist on the instance, and any inherited method that uses them will fail with AttributeError.", "meta": {"difficulty": 1, "interview": true, "concepts": ["inheritance", "super"], "recuerda_de": "m3-oop"}}'::jsonb where id = 'm4-e1';
update exercises set content = '{"prompt": "What does this print? Pay attention to the order in which try, except, else, and finally run.", "code": "def divide(a, b):\n    try:\n        r = a / b\n    except ZeroDivisionError:\n        print(''division by zero'')\n        return None\n    else:\n        print(''no error'')\n        return r\n    finally:\n        print(''cleanup'')\n\nprint(divide(6, 3))\nprint(divide(1, 0))", "expected_output": "no error\ncleanup\n2.0\ndivision by zero\ncleanup\nNone", "explanation": "else only runs if there was no exception; finally always runs, even after a return. That''s why ''cleanup'' appears before the outer print shows the returned value.", "meta": {"difficulty": 2, "interview": true, "concepts": ["try/except/else/finally"]}}'::jsonb where id = 'm4-e2';
update exercises set content = '{"prompt": "What does this print? Think about which exception gets raised and which clause catches it.", "code": "d = {''a'': 1}\ntry:\n    x = d[''b'']\nexcept (KeyError, IndexError) as e:\n    print(type(e).__name__, e)\ntry:\n    int(''12x'')\nexcept ValueError as e:\n    print(''value:'', e)", "expected_output": "KeyError ''b''\nvalue: invalid literal for int() with base 10: ''12x''", "explanation": "Accessing a non-existent key raises KeyError, whose message is the key in quotes. int(''12x'') isn''t a TypeError (the type is correct, str) but a ValueError: the value isn''t convertible.", "meta": {"difficulty": 2, "interview": false, "concepts": ["exception hierarchy", "KeyError", "ValueError"]}}'::jsonb where id = 'm4-e3';
update exercises set content = '{"prompt": "Order the lines to define a custom exception with an extra attribute and raise it from a validation function.", "lines": ["class InvalidAge(ValueError):", "    def __init__(self, age):", "        super().__init__(f''invalid age: {age}'')", "        self.age = age", "", "def validate(age):", "    if age < 0 or age > 150:", "        raise InvalidAge(age)", "    return age"], "meta": {"difficulty": 2, "interview": false, "concepts": ["custom exceptions"]}}'::jsonb where id = 'm4-e4';
update exercises set content = '{"prompt": "This function reads numbers from a list of strings and adds up the valid ones. It has two problems: it catches too much (it even swallows Ctrl+C) and the `finally` clobbers the result. Fix it.", "starter_code": "def sum_valid(values):\n    total = 0\n    for v in values:\n        try:\n            total += int(v)\n        except:\n            pass\n    try:\n        return total\n    finally:\n        return -1", "tests": [{"call": "sum_valid([''1'', ''2'', ''x'', ''3''])", "expected": "6"}, {"call": "sum_valid([])", "expected": "0"}, {"call": "sum_valid([''10'', None, ''5''])", "expected": "15"}], "hints": ["A bare except catches BaseException, including KeyboardInterrupt and SystemExit. Catch only what you expect.", "int(None) raises TypeError, int(''x'') raises ValueError: catch both explicitly.", "A return inside finally overrides any earlier return: remove that finally."], "solution": "def sum_valid(values):\n    total = 0\n    for v in values:\n        try:\n            total += int(v)\n        except (ValueError, TypeError):\n            pass\n    return total", "meta": {"difficulty": 2, "interview": true, "concepts": ["bare except", "finally", "return"]}}'::jsonb where id = 'm4-e5';
update exercises set content = '{"prompt": "The function should convert to float and, if it fails, raise its own ValueError with the message ''not a number: <text>'' while preserving the original cause (chained with `from`). Right now it loses the cause and changes the exception type. Fix it. Don''t touch the marked block.", "starter_code": "# --- do not touch ---\ndef capture(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e), type(e.__cause__).__name__)\n# --- end ---\n\ndef to_float(text):\n    try:\n        return float(text)\n    except ValueError:\n        raise TypeError(''not a number'')", "tests": [{"call": "to_float(''3.5'')", "expected": "3.5"}, {"call": "capture(lambda: to_float(''abc''))", "expected": "(''ValueError'', ''not a number: abc'', ''ValueError'')"}], "hints": ["Keep the ValueError type: the caller expects a value error, not a type error.", "Include the problematic text in the message so the error is actionable.", "raise ValueError(f''not a number: {text}'') from e"], "solution": "# --- do not touch ---\ndef capture(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e), type(e.__cause__).__name__)\n# --- end ---\n\ndef to_float(text):\n    try:\n        return float(text)\n    except ValueError as e:\n        raise ValueError(f''not a number: {text}'') from e", "meta": {"difficulty": 3, "interview": true, "concepts": ["raise from", "chaining exceptions"]}}'::jsonb where id = 'm4-e6';
update exercises set content = '{"prompt": "Write `parse_age(text)` that returns an int. It must raise ValueError if the text isn''t an integer, and ValueError with the message ''out of range'' if it''s not between 0 and 150. Surrounding whitespace is ignored. Don''t touch the marked block.", "starter_code": "# --- do not touch ---\ndef capture(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e))\n# --- end ---\n\ndef parse_age(text):\n    pass", "tests": [{"call": "parse_age('' 42 '')", "expected": "42"}, {"call": "capture(lambda: parse_age(''abc''))[0]", "expected": "''ValueError''"}, {"call": "capture(lambda: parse_age(''200''))", "expected": "(''ValueError'', ''out of range'')"}], "hints": ["int() already raises ValueError on non-numeric text: you don''t need to check it by hand.", "After converting, validate the range and raise your own ValueError with the exact message.", "age = int(text.strip()); if not 0 <= age <= 150: raise ValueError(''out of range'')"], "solution": "# --- do not touch ---\ndef capture(fn):\n    try:\n        fn()\n        return None\n    except Exception as e:\n        return (type(e).__name__, str(e))\n# --- end ---\n\ndef parse_age(text):\n    age = int(text.strip())\n    if not 0 <= age <= 150:\n        raise ValueError(''out of range'')\n    return age", "meta": {"difficulty": 2, "interview": false, "concepts": ["validation", "raise"]}}'::jsonb where id = 'm4-e7';
update exercises set content = '{"prompt": "Flip the role: you''re given two implementations of `average(numbers)`, one correct and one with a bug (divides by len+1). Write `test_average(impl)` using `assert` so it FAILS with the broken implementation and PASSES with the correct one. Don''t touch the marked block.", "starter_code": "# --- do not touch ---\ndef average_ok(numbers):\n    return sum(numbers) / len(numbers)\n\ndef average_bug(numbers):\n    return sum(numbers) / (len(numbers) + 1)\n\ndef raises_assertion(fn):\n    try:\n        fn()\n        return False\n    except AssertionError:\n        return True\n# --- end ---\n\ndef test_average(impl):\n    pass", "tests": [{"call": "raises_assertion(lambda: test_average(average_bug))", "expected": "True"}, {"call": "raises_assertion(lambda: test_average(average_ok))", "expected": "False"}], "hints": ["A test is just a function that calls the implementation with known data and compares with assert.", "Pick a case where the bug shows up: with [2, 4] the correct average is 3.0 and the broken one is 2.0.", "assert impl([2, 4]) == 3.0"], "solution": "# --- do not touch ---\ndef average_ok(numbers):\n    return sum(numbers) / len(numbers)\n\ndef average_bug(numbers):\n    return sum(numbers) / (len(numbers) + 1)\n\ndef raises_assertion(fn):\n    try:\n        fn()\n        return False\n    except AssertionError:\n        return True\n# --- end ---\n\ndef test_average(impl):\n    assert impl([2, 4]) == 3.0\n    assert impl([10]) == 10.0", "meta": {"difficulty": 3, "interview": true, "concepts": ["writing tests", "assert"]}}'::jsonb where id = 'm4-e8';
update exercises set content = '{"prompt": "Write a test class with `unittest` for the given `is_palindrome` function: one method that checks a palindrome, another that checks a non-palindrome, and another that checks that case is ignored. The class must be called `TestPalindrome`. Don''t touch the marked block.", "starter_code": "import unittest, io\n\n# --- do not touch ---\ndef is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]\n\ndef run_suite(cls):\n    suite = unittest.TestLoader().loadTestsFromTestCase(cls)\n    r = unittest.TextTestRunner(stream=io.StringIO()).run(suite)\n    return (r.testsRun, len(r.failures) + len(r.errors))\n# --- end ---\n\nclass TestPalindrome(unittest.TestCase):\n    pass", "tests": [{"call": "run_suite(TestPalindrome)", "expected": "(3, 0)"}], "hints": ["Each test method starts with test_ and takes self.", "Use self.assertTrue / self.assertFalse instead of plain assert: they give better messages.", "def test_ignores_case(self): self.assertTrue(is_palindrome(''Anna''))"], "solution": "import unittest, io\n\n# --- do not touch ---\ndef is_palindrome(s):\n    s = s.lower()\n    return s == s[::-1]\n\ndef run_suite(cls):\n    suite = unittest.TestLoader().loadTestsFromTestCase(cls)\n    r = unittest.TextTestRunner(stream=io.StringIO()).run(suite)\n    return (r.testsRun, len(r.failures) + len(r.errors))\n# --- end ---\n\nclass TestPalindrome(unittest.TestCase):\n    def test_palindrome(self):\n        self.assertTrue(is_palindrome(''level''))\n\n    def test_not_palindrome(self):\n        self.assertFalse(is_palindrome(''hello''))\n\n    def test_ignores_case(self):\n        self.assertTrue(is_palindrome(''Anna''))", "meta": {"difficulty": 2, "interview": false, "concepts": ["unittest", "TestCase"]}}'::jsonb where id = 'm4-e9';
update exercises set content = '{"prompt": "Implement a `Timer` context manager to use with `with`, that records in `self.seconds` how long the block took (use `time.perf_counter()`) and does NOT silence exceptions. Don''t touch the marked block.", "starter_code": "import time\n\nclass Timer:\n    pass\n\n# --- do not touch ---\ndef measure():\n    with Timer() as t:\n        x = sum(range(1000))\n    return t.seconds >= 0\n\ndef propagates():\n    try:\n        with Timer():\n            raise ValueError(''boom'')\n    except ValueError:\n        return ''propagated''\n    return ''silenced''\n# --- end ---", "tests": [{"call": "measure()", "expected": "True"}, {"call": "propagates()", "expected": "''propagated''"}], "hints": ["A context manager needs __enter__ (returns self) and __exit__(self, exc_type, exc, tb).", "Store perf_counter() in __enter__ and compute the difference in __exit__.", "If __exit__ returns False (or None), the exception propagates. Returning True would silence it."], "solution": "import time\n\nclass Timer:\n    def __enter__(self):\n        self._t0 = time.perf_counter()\n        return self\n\n    def __exit__(self, exc_type, exc, tb):\n        self.seconds = time.perf_counter() - self._t0\n        return False\n\n# --- do not touch ---\ndef measure():\n    with Timer() as t:\n        x = sum(range(1000))\n    return t.seconds >= 0\n\ndef propagates():\n    try:\n        with Timer():\n            raise ValueError(''boom'')\n    except ValueError:\n        return ''propagated''\n    return ''silenced''\n# --- end ---", "meta": {"difficulty": 3, "interview": true, "concepts": ["context manager", "__enter__/__exit__"]}}'::jsonb where id = 'm4-e10';
update exercises set content = '{"isCode": false, "prompt": "Interview: why is `except Exception: pass` bad practice in production code? Give two reasons and one acceptable alternative.", "modelAnswer": "1) It hides real errors: the program keeps running with inconsistent state and the failure shows up far from its cause. 2) It makes debugging impossible because there''s no trace left. Alternative: catch only the exceptions you expect, and if you truly need to continue, log the error (logging.exception) and explicitly decide what to do.", "meta": {"difficulty": 2, "interview": true, "concepts": ["error handling"]}}'::jsonb where id = 'm4-e11';
update exercises set content = '{"isCode": false, "prompt": "Interview: in your rag-finance project you evaluated with RAGAS. What''s the difference between a classic unit test of a function and evaluating an LLM system? What can you claim with each one?", "modelAnswer": "A unit test is deterministic: same input, same output, pass or fail. An LLM evaluation is statistical: it measures metrics (faithfulness, recall) over a set of cases, and the output varies. With the test you claim correctness of a unit; with the evaluation you claim a quality trend and detect regressions when you change prompts, chunking, or the model.", "meta": {"difficulty": 3, "interview": true, "concepts": ["testing vs evaluation", "RAGAS"]}}'::jsonb where id = 'm4-e12';
update exercises set content = '{"prompt": "What''s the difference between `raise X from e` and `raise X` inside an except?", "answer": "from e links the new exception to its cause (__cause__) and the traceback shows ''The above exception was the direct cause''. Without from, Python only keeps the implicit context.", "explanation": "Chaining preserves debugging information when translating low-level errors into domain errors.", "meta": {"difficulty": 2, "interview": false, "concepts": ["raise from"]}}'::jsonb where id = 'm4-e13';
update exercises set content = '{"prompt": "What exception does int(''3.5'') raise? And int(None)?", "answer": "int(''3.5'') raises ValueError (correct type, invalid value). int(None) raises TypeError (type not convertible).", "explanation": "ValueError = the type is right but the content isn''t; TypeError = the type itself is wrong.", "meta": {"difficulty": 1, "interview": false, "concepts": ["ValueError vs TypeError"]}}'::jsonb where id = 'm4-e14';
update exercises set content = '{"prompt": "In pytest, how do you check that a function raises an exception?", "answer": "with pytest.raises(ValueError): function()", "explanation": "In unittest the equivalent is with self.assertRaises(ValueError):. pytest isn''t available in Pyodide, but it''s what you''ll use in any real repo.", "meta": {"difficulty": 1, "interview": false, "concepts": ["pytest.raises"]}}'::jsonb where id = 'm4-e15';
update exercises set content = '{"prompt": "What''s the base class of all the exceptions you should normally catch?", "answer": "Exception. BaseException also includes KeyboardInterrupt, SystemExit, and GeneratorExit, which you almost never want to intercept.", "explanation": "That''s why a bare except: is dangerous: it''s equivalent to except BaseException.", "meta": {"difficulty": 1, "interview": true, "concepts": ["exception hierarchy"]}}'::jsonb where id = 'm4-e16';
update exercises set content = '{"prompt": "What''s a fixture in testing?", "answer": "Code that prepares the state a test needs (data, connections, temp files) and cleans it up afterward. In unittest: setUp/tearDown; in pytest: functions decorated with @pytest.fixture.", "explanation": "It avoids repeating setup in every test and isolates tests from each other.", "meta": {"difficulty": 1, "interview": false, "concepts": ["fixtures"]}}'::jsonb where id = 'm4-e17';
update exercises set content = '{"isCode": false, "prompt": "Warm-up (M4): in what order do `try`, `except`, `else`, and `finally` run, and which one always runs?", "modelAnswer": "try first; if there''s an exception, except; if not, else; finally always runs at the end, whether or not there was an exception and even if there was a return.", "meta": {"difficulty": 1, "interview": false, "concepts": ["try/except"], "recuerda_de": "m4-testing-errors"}}'::jsonb where id = 'm5-e1';
update exercises set content = '{"prompt": "What does this print? Here the coroutines are awaited one after another.", "code": "import asyncio\n\nasync def task(name, n):\n    print(''start'', name)\n    await asyncio.sleep(0)\n    print(''end'', name)\n    return n * 2\n\nasync def main():\n    a = await task(''A'', 1)\n    b = await task(''B'', 2)\n    print(a + b)\n\nasyncio.run(main())", "expected_output": "start A\nend A\nstart B\nend B\n6", "explanation": "await on a coroutine runs it to completion before continuing. There''s no concurrency here: B doesn''t start until A finishes, even though A yielded control with sleep(0), because nothing else was waiting.", "meta": {"difficulty": 2, "interview": true, "concepts": ["sequential await"]}}'::jsonb where id = 'm5-e2';
update exercises set content = '{"prompt": "What does this print now, with gather? Pay attention to how the prints interleave.", "code": "import asyncio\n\nasync def task(name, n):\n    print(''start'', name)\n    await asyncio.sleep(0)\n    print(''end'', name)\n    return n * 2\n\nasync def main():\n    r = await asyncio.gather(task(''A'', 1), task(''B'', 2))\n    print(r)\n\nasyncio.run(main())", "expected_output": "start A\nstart B\nend A\nend B\n[2, 4]", "explanation": "gather schedules both coroutines. A runs until its first await and yields; then B runs until its own; then A resumes and finishes, followed by B. gather returns the results in the order they were passed, not the order they finished.", "meta": {"difficulty": 2, "interview": true, "concepts": ["gather", "event loop"]}}'::jsonb where id = 'm5-e3';
update exercises set content = '{"prompt": "What does this print? There''s a trap here: one of the functions never yields control.", "code": "import asyncio\n\nasync def blocking():\n    print(''blocking starts'')\n    total = sum(range(100))\n    print(''blocking ends'', total)\n\nasync def fast():\n    print(''fast'')\n\nasync def main():\n    await asyncio.gather(blocking(), fast())\n\nasyncio.run(main())", "expected_output": "blocking starts\nblocking ends 4950\nfast", "explanation": "async doesn''t mean parallel. blocking has no await at all, so it occupies the thread until it''s done; fast only runs once blocking gives control back. For CPU-bound work, async doesn''t help: you need processes or threads.", "meta": {"difficulty": 3, "interview": true, "concepts": ["CPU-bound", "cooperative"]}}'::jsonb where id = 'm5-e4';
update exercises set content = '{"prompt": "Order the lines to download (simulated) several URLs concurrently with gather.", "lines": ["import asyncio", "", "async def download(url):", "    await asyncio.sleep(0.01)", "    return f''content from {url}''", "", "async def main(urls):", "    tasks = [download(u) for u in urls]", "    return await asyncio.gather(*tasks)"], "meta": {"difficulty": 2, "interview": false, "concepts": ["gather", "coroutines"]}}'::jsonb where id = 'm5-e5';
update exercises set content = '{"prompt": "The function should sum up the results of several coroutines. Right now it fails because it forgets to await the coroutines: it sums coroutine objects instead of numbers. Fix it while keeping the concurrency.", "starter_code": "import asyncio\n\nasync def value(n):\n    await asyncio.sleep(0)\n    return n\n\nasync def sum_values(ns):\n    results = [value(n) for n in ns]\n    return sum(results)", "tests": [{"call": "await sum_values([1, 2, 3])", "expected": "6"}, {"call": "await sum_values([])", "expected": "0"}], "hints": ["Calling an async function returns a coroutine, not its result.", "gather accepts several coroutines and returns a list with their results once all of them finish.", "results = await asyncio.gather(*[value(n) for n in ns])"], "solution": "import asyncio\n\nasync def value(n):\n    await asyncio.sleep(0)\n    return n\n\nasync def sum_values(ns):\n    results = await asyncio.gather(*[value(n) for n in ns])\n    return sum(results)", "meta": {"difficulty": 2, "interview": true, "concepts": ["forgotten await", "gather"]}}'::jsonb where id = 'm5-e6';
update exercises set content = '{"prompt": "Write `async def with_timeout(coro, seconds)` that returns the coroutine''s result, or the string ''timeout'' if it takes longer than that. Use `asyncio.wait_for`.", "starter_code": "import asyncio\n\nasync def slow_task(s):\n    await asyncio.sleep(s)\n    return ''ok''\n\nasync def with_timeout(coro, seconds):\n    pass", "tests": [{"call": "await with_timeout(slow_task(0.01), 1)", "expected": "''ok''"}, {"call": "await with_timeout(slow_task(0.2), 0.01)", "expected": "''timeout''"}], "hints": ["wait_for wraps a coroutine and raises an exception if it exceeds the time limit.", "The exception is asyncio.TimeoutError (in Python 3.11+ it''s an alias for TimeoutError).", "try: return await asyncio.wait_for(coro, seconds) except asyncio.TimeoutError: return ''timeout''"], "solution": "import asyncio\n\nasync def slow_task(s):\n    await asyncio.sleep(s)\n    return ''ok''\n\nasync def with_timeout(coro, seconds):\n    try:\n        return await asyncio.wait_for(coro, seconds)\n    except asyncio.TimeoutError:\n        return ''timeout''", "meta": {"difficulty": 2, "interview": false, "concepts": ["wait_for", "timeouts"]}}'::jsonb where id = 'm5-e7';
update exercises set content = '{"prompt": "Write `async def limit_concurrency(coroutines, max_concurrent)` that runs the coroutines with at most `max_concurrent` in flight at a time, using `asyncio.Semaphore`, and returns the list of results in order. This is the pattern you use to avoid overwhelming an LLM API with requests.", "starter_code": "import asyncio\n\nasync def limit_concurrency(coroutines, max_concurrent):\n    pass\n\nasync def echo(x):\n    await asyncio.sleep(0)\n    return x", "tests": [{"call": "await limit_concurrency([echo(1), echo(2), echo(3)], 2)", "expected": "[1, 2, 3]"}, {"call": "await limit_concurrency([], 5)", "expected": "[]"}], "hints": ["A Semaphore(n) lets n coroutines through at a time; the rest wait on acquire.", "Wrap each coroutine in an inner function that does async with sem: return await coro.", "return await asyncio.gather(*[wrapped(c) for c in coroutines])"], "solution": "import asyncio\n\nasync def limit_concurrency(coroutines, max_concurrent):\n    sem = asyncio.Semaphore(max_concurrent)\n\n    async def wrapped(c):\n        async with sem:\n            return await c\n\n    return await asyncio.gather(*[wrapped(c) for c in coroutines])\n\nasync def echo(x):\n    await asyncio.sleep(0)\n    return x", "meta": {"difficulty": 3, "interview": true, "concepts": ["Semaphore", "rate limiting"]}}'::jsonb where id = 'm5-e8';
update exercises set content = '{"prompt": "Write `async def count_failures(coros)` that runs the coroutines with gather and `return_exceptions=True`, and returns the number of results that were exceptions.", "starter_code": "import asyncio\n\nasync def ok():\n    return 1\n\nasync def fail_task():\n    raise ValueError(''x'')\n\nasync def count_failures(coros):\n    pass", "tests": [{"call": "await count_failures([ok(), fail_task(), ok(), fail_task()])", "expected": "2"}, {"call": "await count_failures([ok()])", "expected": "0"}], "hints": ["Without return_exceptions, gather propagates the first exception and you lose the rest.", "With return_exceptions=True the exceptions show up as objects in the results list.", "return sum(isinstance(r, Exception) for r in results)"], "solution": "import asyncio\n\nasync def ok():\n    return 1\n\nasync def fail_task():\n    raise ValueError(''x'')\n\nasync def count_failures(coros):\n    results = await asyncio.gather(*coros, return_exceptions=True)\n    return sum(isinstance(r, Exception) for r in results)", "meta": {"difficulty": 2, "interview": false, "concepts": ["return_exceptions", "gather"]}}'::jsonb where id = 'm5-e9';
update exercises set content = '{"isCode": false, "prompt": "Interview: explain the difference between concurrency and parallelism, and why asyncio gives you the first but not the second.", "modelAnswer": "Concurrency is managing several tasks at once by interleaving them; parallelism is running them literally at the same time on multiple cores. asyncio runs on a single thread with an event loop: when a task waits on I/O (await), it hands control to another. Two things are never running at the same instant, so for CPU-bound work it doesn''t speed anything up; for I/O-bound work (APIs, network, disk) it does, because the waiting time gets put to use.", "meta": {"difficulty": 2, "interview": true, "concepts": ["concurrency vs parallelism"]}}'::jsonb where id = 'm5-e10';
update exercises set content = '{"isCode": false, "prompt": "Interview: in a RAG pipeline you need to generate embeddings for 5,000 chunks by calling an API. How would you use asyncio, and what limit would you need to respect?", "modelAnswer": "I''d fire off the calls concurrently with gather, but bounded by a Semaphore (e.g. 10-20 in flight) to respect the API''s rate limit, with retries and backoff on 429 errors, and batching chunks together if the API supports it. The bottleneck is the network, not the CPU, so async is a good fit.", "meta": {"difficulty": 3, "interview": true, "concepts": ["async in RAG", "rate limit"]}}'::jsonb where id = 'm5-e11';
update exercises set content = '{"prompt": "What does calling a function defined with `async def` return, without await?", "answer": "A coroutine object that hasn''t run yet. It only runs once you await it or schedule it as a task.", "explanation": "It''s the most common mistake: summing, printing, or returning coroutines instead of results.", "meta": {"difficulty": 1, "interview": true, "concepts": ["coroutines"]}}'::jsonb where id = 'm5-e12';
update exercises set content = '{"prompt": "Difference between `await coro()` and `asyncio.create_task(coro())`?", "answer": "await waits for the result right there. create_task schedules the coroutine on the loop and returns a Task immediately, which runs in the background until you await it.", "explanation": "create_task is what lets you fire something off and keep doing other things.", "meta": {"difficulty": 2, "interview": true, "concepts": ["create_task"]}}'::jsonb where id = 'm5-e13';
update exercises set content = '{"prompt": "What does `asyncio.gather(*coros)` do?", "answer": "Runs all the coroutines concurrently and returns a list with their results in the same order they were passed.", "explanation": "If one fails, it propagates the exception unless you use return_exceptions=True.", "meta": {"difficulty": 1, "interview": false, "concepts": ["gather"]}}'::jsonb where id = 'm5-e14';
update exercises set content = '{"prompt": "Why is `time.sleep(1)` inside a coroutine a mistake?", "answer": "Because it blocks the entire thread and no other task can make progress. You need to use await asyncio.sleep(1).", "explanation": "Any blocking call (requests, time.sleep, long computations) freezes the event loop.", "meta": {"difficulty": 1, "interview": true, "concepts": ["blocking the loop"]}}'::jsonb where id = 'm5-e15';

update lessons set title = 'Doing exceptions right' where id = 'm4-l1';
update lessons set title = 'Testing with unittest and assert' where id = 'm4-l2';
update lessons set title = 'What to test and what not to' where id = 'm4-l3';
update lessons set title = 'Concurrency is not parallelism' where id = 'm5-l1';
update lessons set title = 'await, gather, and the event loop' where id = 'm5-l2';
update lessons set title = 'Patterns you''ll actually use: limits, timeouts, and retries' where id = 'm5-l3';

update lessons set content_md = $md$**Before reading, predict:** what's the difference between `int('3.5')` and `int(None)`?

## The idea
Exceptions form a hierarchy. `Exception` is the root of the ones you should catch; `BaseException` also includes `KeyboardInterrupt` and `SystemExit`, which you almost never want to intercept. `ValueError` means "right type, invalid value"; `TypeError`, "wrong type". Catch **only what you expect**, and as specifically as possible.

When you translate a low-level error into a domain one, chain it with `from` so you don't lose the cause:
```python
try:
    return float(text)
except ValueError as e:
    raise ValueError(f'not a number: {text}') from e
```

## The order of execution
`try` -> if there's an exception, `except`; if not, `else` -> `finally` **always**, even after a `return`.

## The typical mistake
A bare `except:` or `except Exception: pass`. It hides the failure, leaves inconsistent state, and makes debugging impossible. If you really need to keep going, log the error (`logging.exception`) and decide explicitly.

## What they ask in interviews
"Why is an empty `except` dangerous?" and "What does `raise ... from` do?". Both are filter questions: they separate someone who has debugged production from someone who hasn't.
$md$ where id = 'm4-l1';
update lessons set content_md = $md$**Before reading, predict:** can a test with no `assert` at all still fail?

## The idea
A test is a function that calls your code with known data and checks the result. With `unittest`, you group tests in a class that inherits from `TestCase`; each `test_*` method is a case; `setUp` prepares shared state. `assertEqual`, `assertTrue`, `assertRaises` give better messages than a plain `assert`.

```python
import unittest

class TestParseAge(unittest.TestCase):
    def test_valid(self):
        self.assertEqual(parse_age(' 42 '), 42)
    def test_invalid(self):
        with self.assertRaises(ValueError):
            parse_age('abc')
```
`pytest` (not available in the browser, but available in any real repo) simplifies this: plain functions with `assert`, and `pytest.raises` for exceptions.

## Failure vs error
A **failure** is an assertion that isn't met: your code does something else. An **error** is an unexpected exception: the test couldn't even finish.

## The typical mistake
Only testing the happy path. Every function with validation needs at least one test for the invalid case and one for a boundary (0, empty, None).

## What they ask in interviews
"How do you test that a function raises an exception?" -- `assertRaises` / `pytest.raises`. "What's a fixture?" -- shared setup and teardown code across tests.
$md$ where id = 'm4-l2';
update lessons set content_md = $md$**Before reading, predict:** does it make sense to write a test for `sum(numbers) / len(numbers)`?

## The idea
Test **observable behavior**, not implementation: what it returns, what it raises, what effect it leaves. Test the decisions (branches, validations, boundaries) and the transformations you wrote yourself. Don't test the language or the standard library, or internal details you might refactor tomorrow.

A good test is **deterministic** (same result every time), **isolated** (doesn't depend on other tests or the network), and **fast**. When something external gets in the way (an API, a clock, a database), replace it with a double: an object that behaves the same way as far as your code is concerned.

## Priority example
For `parse_age`: yes to `' 42 '`, `'abc'`, `'200'`, `'-1'`, `''`. No to "does `int()` work".

## Testing and LLM systems
A unit test is pass/fail. An LLM system gets **evaluated**: metrics over a fixed dataset (faithfulness, recall), compared across versions. The first checks correctness of a unit; the second, a quality trend. Both coexist in an AI project: tests for chunking, parsing, and logic; evaluation for the model's output.

## What they ask in interviews
"How do you test code that calls an LLM API?" -- by injecting a fake client that returns scripted responses, and reserving the real model only for end-to-end evaluation.
$md$ where id = 'm4-l3';
update lessons set content_md = $md$**Before reading, predict:** does an `asyncio` program use more than one CPU core?

## The idea
**Concurrency**: managing several tasks by interleaving them. **Parallelism**: running them literally at the same time on multiple cores. `asyncio` gives you the first, not the second: a single thread with an *event loop* that jumps from one task to another every time one does `await` (waits on I/O). While one waits for an API response, another makes progress.

That's why async speeds up **I/O-bound** work (network, disk, APIs) and does nothing for **CPU-bound** work (heavy computation). For CPU you need processes (`multiprocessing`) or, in Python 3.13+, threads without the GIL.

## Example
Five API calls of 1 s each: sequential takes 5 s; with `gather`, ~1 s. Five 1-second CPU computations: with `asyncio` they're still 5 s.

## The typical mistake
Putting something blocking inside a coroutine: `time.sleep`, `requests.get`, a long loop. It freezes the whole loop; no other task makes progress. Use `asyncio.sleep`, an async HTTP client, or `run_in_executor`.

## What they ask in interviews
"Explain concurrency vs parallelism and where asyncio fits." It's the number-one async question. The short answer: one thread, cooperative, wins on I/O waits.
$md$ where id = 'm5-l1';
update lessons set content_md = $md$**Before reading, predict:** what does `task()` return if `task` is `async def` and you don't put `await`?

## The idea
Calling an `async def` **doesn't run it**: it returns a coroutine object. It runs when you `await` it (wait for its result right there) or schedule it with `asyncio.create_task` (runs in the background). `asyncio.gather(*coros)` schedules several, interleaves them, and returns their results **in the order you passed them**.

```python
async def main():
    a = await task('A')                  # sequential: B waits for A
    r = await asyncio.gather(task('B'), task('C'))  # concurrent
```
The loop only switches tasks at an `await`. A coroutine with no `await` at all runs straight through without yielding.

## The typical mistake
Summing, printing, or returning coroutines instead of results (`sum([f(x) for x in xs])` with an async `f`). The symptom is a `TypeError` with "coroutine" in the message, or a `RuntimeWarning: coroutine was never awaited`.

## What they ask in interviews
"Difference between `await` and `create_task`?" -- `await` waits; `create_task` fires and moves on. "What happens if one coroutine in `gather` fails?" -- it propagates the first exception and you lose the rest, unless you pass `return_exceptions=True`.
$md$ where id = 'm5-l2';
update lessons set content_md = $md$**Before reading, predict:** if you fire 5,000 calls to an API with `gather` all at once, what happens?

## The idea
Uncontrolled concurrency turns into an attack on your own provider. Three tools handle 90% of the cases:

- **`Semaphore(n)`**: at most `n` coroutines inside the `async with sem:` block at a time. It's the simplest rate limiter.
- **`wait_for(coro, timeout)`**: raises `TimeoutError` if it takes too long. No external call should ever go out without a timeout.
- **Retry with backoff**: on a 429 or a timeout, wait (0.5 s, 1 s, 2 s...) and retry a bounded number of times.

```python
sem = asyncio.Semaphore(10)
async def embed(chunk):
    async with sem:
        return await asyncio.wait_for(api.embed(chunk), 30)
vectors = await asyncio.gather(*[embed(c) for c in chunks])
```

## The typical mistake
Putting the `Semaphore` outside the function and forgetting the `async with`; or creating the semaphore inside each coroutine (each one gets its own, and it limits nothing).

## What they ask in interviews
"How would you generate embeddings for 5,000 chunks without overwhelming the API?" -- gather + semaphore + timeout + backoff, and batching if the API supports it. It's exactly the question that connects this module to RAG.
$md$ where id = 'm5-l3';
